name = "remix-cloudflare-workers"
type = "javascript"

workers_dev = true

zone_id = ""
account_id = ""
route = ""

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format="service-worker"
